### PR TITLE
Submissions of Ray Team Project

### PR DESCRIPTION
**Pull request by olowoyinka**

### CODE REVIEW

**Comment by mircea-dogaru-redgate** [comment]
Your project is really nice, love the idea.

Just be careful with the video, it's very detailed and that's cool but it should be a 1-3 minutes quick walkthrough :) 

https://github.com/virtualmlnet/hackathon-2020/blob/main/rules.md

**Comment by olowoyinka** [comment]
Thanks @mircea-dogaru-redgate.

**Comment by luisquintanilla** [comment]
Thanks for your submission @olowoyinka. This looks great!

**Comment by Brett-Parker** [comment]
Great work @olowoyinka . Really interesting use case. Great work, good luck!

**Comment by olowoyinka** [comment]
A great thanks @Brett-Parker and @luisquintanilla

**Pull request merged**
